using System.Text.Json.Serialization;

namespace ModelContextProtocol.Interceptors.Protocol.Llm;

/// <summary>
/// Represents a choice in an LLM completion response.
/// </summary>
/// <remarks>
/// Based on the OpenAI chat completion choice format as specified in SEP-1763.
/// </remarks>
public sealed class LlmChoice
{
    /// <summary>
    /// Gets or sets the index of this choice in the list of choices.
    /// </summary>
    [JsonPropertyName("index")]
    public int Index { get; set; }

    /// <summary>
    /// Gets or sets the message generated by the model.
    /// </summary>
    [JsonPropertyName("message")]
    public LlmMessage Message { get; set; } = new();

    /// <summary>
    /// Gets or sets the reason the model stopped generating tokens.
    /// </summary>
    [JsonPropertyName("finish_reason")]
    public LlmFinishReason? FinishReason { get; set; }
}
